DIR = '''
SELECT *
FROM
  (SELECT A.OPERATOR,
    A.ATA,
    ROUND(CAST(A.COUNT_FI AS float)/
    (SELECT COUNT(AU.AU_DATE)
    FROM MAIN_AIRCRAFT_MONTHLY_UTILIZATION AU
    WHERE (AU.AU_DATE BETWEEN '{0}' AND '{1}')
    AND AU.OPERATOR_CODE                =A.OPERATOR_CODE
    ), 4) AS DIR
  FROM
    (SELECT OPERATORS.OPERATOR_NAME AS OPERATOR,
      OPERATORS.OPERATOR_CODE AS OPERATOR_CODE,
      CONCAT(FI.ATA_CAUSE_CHAPTER, FI.ATA_CAUSE_SECTION) AS ATA,
      COUNT(FI.AC_MODEL)      AS COUNT_FI
    FROM MAIN_FLIGHT_INTERRUPTIONS FI LEFT JOIN MAIN_OPERATORS OPERATORS on FI.OPERATOR_CODE=OPERATORS.OPERATOR_CODE
    WHERE (FI.FI_DATE BETWEEN '{0}' AND '{1}')
    AND FI.CHARGEABLE                  ='Y'
    AND FI.AC_MODEL in {2}
    GROUP BY 
      OPERATORS.OPERATOR_NAME,
      OPERATORS.OPERATOR_CODE,
      FI.ATA_CAUSE_CHAPTER,
      FI.ATA_CAUSE_SECTION
    ) A
  ) as b PIVOT( SUM(DIR) FOR operator IN (
  [Air Nostrum],
  [Air Wisconsin],
  [China Express Airlines],
  [CityJet],
  [Endeavor Air],
  [Garuda Indonesia],
  [GoJet Airlines],
  [IBEX Airlines],
  [IrAero],
  [Jazz Aviation],
  [Lufthansa CityLine],
  [Melair],
  [Mesa Airlines],
  [PSA Airlines],
  [Rwandair Express],
  [Skywest],
  [Xfly (formerly Regional Jet OU)])) as pt;
'''

IR = ''''''

operators_regions = '''
SELECT DISTINCT OPERATOR_NAME, CONTINENT_CODE AS REGION
FROM
    (SELECT OPERATORS.OPERATOR_NAME , COUNTRY_CODE
    FROM
        (SELECT DISTINCT(FI.OPERATOR_CODE)
        FROM
            MAIN_FLIGHT_INTERRUPTIONS FI
        WHERE (FI.FI_DATE BETWEEN '2015-01-01' AND GETDATE())) FI,
        MAIN_OPERATORS OPERATORS
    WHERE FI.OPERATOR_CODE=OPERATORS.OPERATOR_CODE) A LEFT JOIN
    MAIN_COUNTRIES COUNTRIES ON A.COUNTRY_CODE=COUNTRIES.COUNTRY_CODE;'''